name: Build and Test
on:
  push:
    tags:
      - v*
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest

      - uses: actions/checkout@v2
      - name: Generate
        run: make generate

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: -v
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Test
        run: make test-only
